[build-system]
requires = [ "setuptools" ]

[project]
name = "taipy_konva"
version = "0.0.1"
authors = [ { name = "Fabien Lelaquais", email = "fabien.lelaquais@taipy.io" } ]
description = "A Taipy GUI extension library that provides Konva functionalities."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
keywords = [ "taipy", "konva" ]
license = {text = "Apache License 2.0"}
classifiers = [
    "Intended Audience :: Developers",
    # "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [ "taipy-gui>=4.0" ]
